# Ref: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml

name: Test

on:

  push:

  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for g++-10
        run:  |
              if ! command -v g++-10 &> /dev/null; then
                echo "g++-10 is not installed"
                exit 1
              else
                echo "g++-10 is installed"
              fi

      - name: Try to compile
        run:  g++-10 -std=gnu++20 -O0 -g -rdynamic test/test.cpp -o test/test.exe

      - name: Try to run executable
        run:  test/test.exe

      - name: Checkout repository
        uses: actions/checkout@v4
