# Ref: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml

name: Test

on:

  push:

  workflow_dispatch:

defaults:

  run:

    shell: bash

jobs:

  check_compiler_availability:

    runs-on: ubuntu-latest

    timeout-minutes: 1

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for g++-10
        run:  |
              if ! command -v g++-10 &> /dev/null; then
                echo "g++-10 is not installed"
                exit 1
              else
                echo "g++-10 is installed"
              fi

  execute_test:

    strategy:

      matrix:

        file: [non_uniform_random_bit_generator, std_mt19937]

    runs-on: ubuntu-latest

    timeout-minutes: 1

    needs: [check_compiler_availability]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Try to compile
        run:  g++-10 -std=gnu++20 -O0 -g -rdynamic test/${{ matrix.file }}.cpp -o test/${{ matrix.file }}.exe

      - name: Try to run executable
        run:  test/${{ matrix.file }}.exe
